### ISSUE TITLE
ImportError: cannot import name search

### ISSUE THREAD

**Issue by VitorSavedra** [the-Infected-Drake/TIDoS-Framework#4]
```sh
python tidos.py

Traceback (most recent call last):
  File "tidos.py", line 10, in <module>
    from googleSearch import *
  File "/opt/tidos/googleSearch.py", line 3, in <module>
    from google import search
ImportError: cannot import name search
```

----

```sh
python tidos/googleSearch:

Traceback (most recent call last):
  File "tidos/googleSearch.py", line 3, in <module>
    from google import search
ImportError: cannot import name search
```

**Comment by the-Infected-Drake** [comment]
## (Solved) ImportError: cannot import name search

Hey there @VitorSavedra, I figured out your problem. Please run the uninstallation file `uninstall.py`, and run the installation file `setup.py` to run the installation file again, so that everything runs fine. Hope this fixes the issue. Also you gonna take note that this tool will run only on Linux systems.

> Good Luck...
**- @_tID**

**Comment by VitorSavedra** [comment]
Hi!

I followed the steps, reinstalled Python and checked the files permissions. But, no success. Possibly, it is a local problem.

My environment:
- Ubuntu 17.04 (Zesty Zapus)
- Python 2.7.13

Thank you for help. \o

**Comment by genesisether** [comment]
I followed the steps, reinstalled tidos but not solve this issue.
